# Generated by Django 3.2.7 on 2021-09-09 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('rating', models.PositiveBigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('product', models.CharField(max_length=100)),
                ('fabric', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('colour', models.CharField(max_length=50)),
                ('size', models.PositiveBigIntegerField()),
                ('print', models.BooleanField()),
                ('image', models.CharField(max_length=300)),
                ('design_drawing', models.CharField(blank=True, max_length=300)),
                ('season', models.CharField(max_length=50)),
                ('center_back_length', models.PositiveBigIntegerField(blank=True, null=True)),
                ('center_front_length', models.PositiveBigIntegerField(blank=True, null=True)),
                ('sleeve_length', models.PositiveBigIntegerField(blank=True, null=True)),
                ('hem_length', models.PositiveBigIntegerField(blank=True, null=True)),
                ('chest', models.PositiveBigIntegerField(blank=True, null=True)),
                ('waist', models.PositiveBigIntegerField(blank=True, null=True)),
                ('inside_leg_length', models.PositiveBigIntegerField(blank=True, null=True)),
                ('outside_leg_length', models.PositiveBigIntegerField(blank=True, null=True)),
            ],
        ),
    ]
