# Generated by Django 3.2.7 on 2021-09-09 18:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('designs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='added_by',
            field=models.ForeignKey(blank='True', on_delete=django.db.models.deletion.DO_NOTHING, related_name='added_designs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='design',
            name='saved_by',
            field=models.ManyToManyField(blank='True', related_name='saved_designs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='design',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='designs.design'),
        ),
        migrations.AddField(
            model_name='comment',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_made', to=settings.AUTH_USER_MODEL),
        ),
    ]
